[package]
name = "hoc"
version = "0.14.4"
authors = ["Valentin Brandl <vbrandl@riseup.net>"]
edition = "2018"
build = "build.rs"

[dependencies]
actix-rt = "1.1.1"
actix-slog = "0.2.1"
actix-web = "3.2.0"
badge = "0.3.0"
bytes = "0.6.0"
futures = "0.3.7"
git2 = "0.13.12"
lazy_static = "1.4.0"
number_prefix = "0.4.0"
openssl-probe = "0.1.2"
reqwest = "0.10.8"
serde = "1.0.117"
serde_derive = "1.0.103"
serde_json = "1.0.59"
slog = "2.5.2"
slog-async = "2.5.0"
slog-atomic = "3.0.0"
slog-term = "2.6.0"
structopt = "0.3.20"
tracing = "0.1.21"
tracing-subscriber = "0.2.14"
tracing-actix-web = "0.2.1"
tracing-futures = "0.2.4"

[build-dependencies]
ructe = "0.12.0"
vergen = "3.1.0"

[dev-dependencies]
tempfile = "3.1.0"
