[package]
name = "hoc"
version = "0.35.0"
authors = ["Valentin Brandl <vbrandl@riseup.net>"]
edition = "2021"
build = "src/build.rs"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "hoc"

[dependencies]
actix-rt = "2.9.0"
actix-web = "4.4.0"
badgers = "1.2.0"
bytes = "1.5.0"
config = { version = "0.13.3", features = ["toml"] }
dotenvy = "0.15.7"
futures = "0.3.28"
git2 = "0.18.0"
lazy_static = "1.4.0"
mime = "0.3"
number_prefix = "0.4.0"
openssl-probe = "0.1.5"
reqwest = "0.11.20"
serde = "1.0.188"
serde_derive = "1.0.166"
serde_json = "1.0.106"
tracing = "0.1.37"
tracing-actix-web = "0.7.6"
tracing-bunyan-formatter = "0.3.9"
tracing-futures = "0.2.5"
tracing-log = "0.1.3"
tracing-subscriber = { version = "0.3.17", features = ["registry", "env-filter"] }

[build-dependencies]
anyhow = "1.0.75"
ructe = { version = "0.17.0", features = ["mime03"] }
vergen = { version = "8.2.5", default-features = false, features = ["git", "gitoxide"] }

[dev-dependencies]
awc = "3.2.0"
ructe = "0.17.0"
tempfile = "3.8.0"
tokio = "1.32.0"
