[package]
name = "hoc"
version = "0.22.4"
authors = ["Valentin Brandl <vbrandl@riseup.net>"]
edition = "2018"
build = "build.rs"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "hoc"

[dependencies]
actix-rt = "2.7.0"
actix-web = "4.1.0"
badge = "0.3.0"
bytes = "1.2.1"
config = { version = "0.13.2", features = ["toml"] }
dotenvy = "0.15.3"
futures = "0.3.24"
git2 = "0.15.0"
lazy_static = "1.4.0"
mime = "0.3"
number_prefix = "0.4.0"
openssl-probe = "0.1.5"
reqwest = "0.11.11"
serde = "1.0.144"
serde_derive = "1.0.137"
serde_json = "1.0.85"
tracing = "0.1.36"
tracing-actix-web = "0.6.0"
tracing-bunyan-formatter = "0.3.3"
tracing-futures = "0.2.5"
tracing-log = "0.1.3"
tracing-subscriber = { version = "0.3.15", features = ["registry", "env-filter"] }

[build-dependencies]
ructe = { version = "0.14.2", features = ["mime03"] }
vergen = { version = "7.3.1", default-features = false, features = ["git"] }

[dev-dependencies]
awc = "3.0.1"
ructe = "0.14.2"
tempfile = "3.3.0"
tokio = "1.20.1"
