[package]
name = "hoc"
version = "0.21.2"
authors = ["Valentin Brandl <vbrandl@riseup.net>"]
edition = "2018"
build = "build.rs"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "hoc"

[dependencies]
actix-rt = "2.6.0"
actix-web = "4.0.0-rc.3"
badge = "0.3.0"
bytes = "1.1.0"
config = { version = "0.11.0", features = ["toml"] }
dotenv = "0.15.0"
futures = "0.3.21"
git2 = "0.14.0"
lazy_static = "1.4.0"
number_prefix = "0.4.0"
openssl-probe = "0.1.5"
reqwest = "0.11.9"
serde = "1.0.136"
serde_derive = "1.0.136"
serde_json = "1.0.79"
tracing = "0.1.31"
tracing-actix-web = "0.5.0-rc.3"
tracing-bunyan-formatter = "0.3.2"
tracing-futures = "0.2.5"
tracing-log = "0.1.2"
tracing-subscriber = { version = "0.3.9", features = ["registry", "env-filter"] }

[build-dependencies]
ructe = "0.14.0"
vergen = { version = "6.0.2", default-features = false, features = ["git"] }

[dev-dependencies]
awc = "3.0.0-beta.21"
ructe = "0.14.0"
tempfile = "3.3.0"
tokio = "1.17.0"
