version: "3"

services:
  hoc:
    image: vbrandl/hits-of-code:latest
    volumes:
      - ./repos:/home/hoc/repos
      - ./cache:/home/hoc/cache
    # ports:
    #   - "127.0.0.1:8080:8080"
    restart: always
    env_file:
      - ./.env
